# Generated by Django 3.2.13 on 2022-06-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('APOS', 'A+'), ('BPOS', 'B+'), ('OPOS', 'O+'), ('ANEG', 'A-'), ('BNEG', 'B-'), ('ONEG', 'O-'), ('ABPOS', 'AB+'), ('ABNEG', 'AB-')], max_length=5, null=True, verbose_name='Blood Group'),
        ),
    ]
